### PR TITLE
NOISSUE Parse META-INF/mods.toml for Forge 1.14+ mod metadata

### PR DESCRIPTION
**Pull request by kumquat-ir**
Enigmatica 6, before and after:
Screenshot_2021-04-16_13-42-03

${file.jarVersion} is what is stored in mods.toml, and seems to be replaced on runtime by Forge itself

This will add a new dependency, [toml11](https://github.com/ToruNiina/toml11), not sure if this should be in a submodule or raw code
Will also allow further parsing of mods.toml, such as for #3536

(this is my first time trying to contribute to a project, please let me know if i did anything wrong!)

### CODE REVIEW

**Review by Janrupf — APPROVED** [review]
Looks good to me. Not exactly sure what the policy on submodules is, it seems to be rather `whatever, everything goes`.

**Comment by jamierocks** [comment]
> ${file.jarVersion} is what is stored in mods.toml, and seems to be replaced on runtime by Forge itself

Yep, `file.jarVersion` is the only supported subtitution at the moment though. The below is my handing in another project.

```go
			// Minecraft Forge supports substitutions in mods.toml files,
			// with data populated from the Jar's MANIFEST.
			// Substitutions are in the form ${file.KEY}.
			for _, mod := range forgeMods {
				if mod.Version == "${file.jarVersion}" {
					manifestVersion := manifest.Main["Implementation-Version"]
					if manifestVersion == "" {
						// This matches Minecraft Forge's behaviour
						manifestVersion = "NONE"
					}

					mod.Version = manifestVersion
				}
			}
```

**Comment by kumquat-ir** [comment]
Added a somewhat ugly solution for that, but works just fine
Thanks for showing me where that information is actually located

**Comment by peterix** [comment]
I prefer raw code. It's MIT licensed, so it can be a static library too... Except it's a header only c++ mess that will make build times even longer than they are now...

How about https://github.com/cktan/tomlc99 instead?

**Comment by kumquat-ir** [comment]
That can be done.  Looks like the author of that already provides a wrapper for that library in c++ (https://github.com/cktan/tomlcpp), but that unfortunately seems to be in c++17.

**Comment by kumquat-ir** [comment]
More verbose now (guess that's just what you get with C libraries), but definitely compiles faster, and works just as well

**Pull request merged**
