### PR TITLE
GH3970: README changes for debrand

### PR DESCRIPTION
**Pull request by bryiewes**

### CODE REVIEW

**Comment by Sebastian-byte** [comment]
Shouldn't be "Launcher" better? Or maybe something similar?

**Comment by kryptochaos** [comment]
It hadnt crossed my mind but yes

**Comment by bryiewes** [comment]
that was unintentional, let me fix that.

**Comment by bryiewes** [comment]
nevermind, im not as familiar with github as i thought i was, ive already modified the fork i made, as shown, so i dont want to use to to PR.

**Pull request closed without merging**
