### PR TITLE
NOISSUE Support ATLauncher optional mods

### PR DESCRIPTION
**Pull request by jamierocks**
This is still very early in development, but this pull request serves to track it's progress.

screenshot of selection dialog

### CODE REVIEW

**Comment by AverageComet250** [comment]
Rather than just for atlauncher, wouldn't this feature be good for all of them?

**Comment by jamierocks** [comment]
This is a platform specific feature, no other platform I'm aware of support anyway.

**Comment by AverageComet250** [comment]
Don't other platforms have optional mods too?

**Comment by jamierocks** [comment]
modpacks.ch has it in metadata, but is unused - as far as I'm aware. There probably is some code that could be shared, but no other use for it yet.

In any case, no platform will have optional mod logic the same as ATLauncher does.

**Comment by peterix** [comment]
Code looks good, I'm just going to merge this and see what happens.

That's what develop is for after all :)

**Pull request merged**
