### PR TITLE
Update Java detection

### PR DESCRIPTION
**Pull request by phit**

### CODE REVIEW

**Comment by jamierocks** [comment]
Are there other distributions we ought to introduce detection for too?

* Red Hat's
* Corretto
* Microsoft's
* ojdkbuild
* any more?

**Comment by RDKRACZ** [comment]
What about Azul Zulu and Bellsoft Liberica?

**Comment by DragonEggBedrockBreaking** [comment]
graalvm?

**Comment by phit** [comment]
by default use the Oracle "JavaSoft" Path and are already picked up through that:

- Corretto
- ojdkbuild



---
added:

- Microsoft
- Bellsoft Liberica
- Azul Zulu

---

Red Hat: needs an account to download unless I'm blind
graalvm: doesn't seem to have an installer for Windows

**Comment by jamierocks** [comment]
> Red Hat: needs an account to download unless I'm blind

It does, yeah.

**Pull request merged**
