### PR TITLE
GH-3857: Remove openjdk-8-jre recommendation

### PR DESCRIPTION
**Pull request by Sebastian-byte**

### CODE REVIEW

**Comment by kb-1000** [comment]
I'd wait with this until downloading Mojang Java runtimes is supported

**Comment by kryptochaos** [comment]
Plus, jre 8 is needed for <1.17

**Comment by Sebastian-byte** [comment]
> Plus, jre 8 is needed for <1.17

Well RPM package doesn't include any JDK, please read the issue for more context.

**Comment by kb-1000** [comment]
Well, the RPM package doesn't do that simply because I forgot adding it.
And I'm also not too sure how I'd even express Recommends in an RPM.
Using that as a reason to justify this change isn't going to work well.

**Comment by peterix** [comment]
Java 8 is required for all versions below 1.17

At some point, we will have a way for the launcher to download its own java runtimes... and then this change will be warranted.

For now, it is not.

**Comment by jamierocks** [comment]
Perhaps the recommendation could be expanded to include Java 16 packages too then?

**Comment by bryiewes** [comment]
The ubuntu repos dont have java 16 yet.

**Pull request closed without merging**
