### PR TITLE
Add ability to select a server to join in the instance settings

### PR DESCRIPTION
**Pull request by Janrupf**
This PR allows to set a server in the instance settings. Additionally it performs DNS lookup using the pattern `_minecraft._tcp.<server address>`, since Minecraft skips this step when using `--server` and `--port`.

I confirmed this to be working from Minecraft 1.0 up to the current version. Older version might work as well, given that they accept the required arguments using the applet wrapper.

Ref:
image

### CODE REVIEW

**Comment by Janrupf** [comment]
This is partially related to #3287, though only implements a part of it.

**Comment by kb-1000** [comment]
Shouldn't that be _tcp and not _tpc?

**Comment by Janrupf** [comment]
Oh yeah, it is... thats like the 10th time that I typo that today. Its correct in the code though :P

**Comment by Janrupf** [comment]
New changes:

- Address and port have been merged and address parsing behaves now like within minecraft itself:
image

- Servers can now be joined (given the instance is not running already) directly from the servers page:
image

**Comment by peterix** [comment]
This looks pretty good.

**Comment by Janrupf** [comment]
Decided to add another feature: MultiMC now accepts `--server` (in combination with `--launch`) on the command line to launch an instance with a specified server. You can now make desktop shortcuts to start your favorite version with specified servers

**Comment by AverageComet250** [comment]
Once this is done, can this be duplicated for worlds?

I'm guessing no since I'm pretty sure there isn't a Minecraft Param for that

**Comment by Janrupf** [comment]
> I'm guessing no since I'm pretty sure there isn't a Minecraft Param for that
Yeah, sadly this will not be possible without mods

**Comment by peterix** [comment]
Let's merge this and see what happens.

**Pull request merged**
