### PR TITLE
Remove Username wording from dialogs

### PR DESCRIPTION
**Pull request by S10MC2015**
In response to #2839,

Fix dialogues and things to reflect change where you need to use an email to login; legacy or not.

### CODE REVIEW

**Comment by S10MC2015** [comment]
sorry about the many commits

**Comment by phit** [comment]
afaik unmigrated accounts still exist? or did this change recently?
https://help.mojang.com/customer/en/portal/articles/329527-minecraft-log-in

**Comment by S10MC2015** [comment]
@phit they still exist but you have to login through the linked email address regardless of migration status now.

**Comment by peterix** [comment]
I used the idea of this. So, it is merged, in essence.

Please. if you make a pull request, make sure the commits and sommit messages are in order. They are directly used as the changhelog for development versions, and I couldn't use this directly because of that. 

Anyway, it's there.

**Pull request closed without merging**
