### PR TITLE
Change default PermGen from 64 to 128 mb

### PR DESCRIPTION
**Pull request by Greenphlem**
This will help users who run mods. Too many issues have been made over the lack of more permgen being assigned.

### CODE REVIEW

**Comment by Heufneutje** [comment]
Won't this change cause the warning to appear for everyone who uses Java 8 though? There's a lot of people complaining about that too.

**Comment by Kilobyte22** [comment]
Does MultiMC even set permgen when java8 is in use?

**Comment by 02JanDal** [comment]
Yes, since we currently don't have a reliable way of determining which version of Java is used.

**Comment by Kilobyte22** [comment]
Wouldn't a java --version do the job?

**Comment by 02JanDal** [comment]
Nope, the output isn't really reliable. We currently have a simple java program that dumps the java version from a system property, but going from there to the boolean value of (java < 8) is the hard part.

**Comment by peterix** [comment]
It can be done at the cost of running more java processes. Run java once to find out what version you are working with, run it second time for real, with the right parameters.

**Comment by Heufneutje** [comment]
And besides, once Java 7 support is dropped the problem should sort itself out.

**Comment by Greenphlem** [comment]
Right but currently more than around 50% of purple use java 7 or less, so
it's still a problem.

**Comment by Greenphlem** [comment]
People* idiot phone

**Comment by peterix** [comment]
Well, merged. And added the necessary bits for the warnings from java 8 to not show up in the console.

**Pull request merged**
