### PR TITLE
Add Windows instructions to build from command line.

### PR DESCRIPTION
**Pull request by 44trent3**
Not much to say. Just added some instructions to build from command line on Windows.

### CODE REVIEW

**Comment by peterix** [comment]
Looks good to me :)

Please squash those commits into one and use this commit message:
```
NOISSUE Add Windows instructions to build from command line.
```

**Comment by 44trent3** [comment]
Okay, I just squashed the commits.

**Comment by peterix** [comment]
Well. Now it's even more commits... You may have to get to know your tools better.

For now, I'll do it manually.

**Comment by peterix** [comment]
Alright... manually cherry-picked the one commit out of this :)

You might want to reset your develop branch.

**Pull request closed without merging**
