### PR TITLE
Remove broken Mojang services status

### PR DESCRIPTION
**Pull request by kb-1000**
This can be reverted once the status service is fixed.

### CODE REVIEW

**Comment by peterix** [comment]
Is it really this broken, and needs to be removed?

**Comment by kb-1000** [comment]
Well, I would answer that with yes. However I can only really see that the Session indicator is broken and not if the other ones are as well. As you work at Mojang, do _you_ know that?

**Comment by OpenDeveloper16** [comment]
Yea the Session part of the status toolbar is broken... I can't figure out how to upload a picture though

**Comment by OpenDeveloper16** [comment]
Annotation 2020-08-13 092318

**Comment by OpenDeveloper16** [comment]
There we go

**Comment by Zetabite** [comment]
I agree that it should be removed as of now, as most people ask if that has to do with the problem they are having or write this is a problem to begin with

**Comment by Janrupf** [comment]
Can be closed now, superseded by #3524

**Comment by kb-1000** [comment]
Since now the Mojang status check API has been removed entirely, I'm reopening this PR.

**Comment by kb-1000** [comment]
... if GitHub allowed me to? Apparently, it doesn't like that I force pushed to the branch.

**Pull request closed without merging**
