### PR TITLE
NOISSUE Add ATLauncher modpack search

### PR DESCRIPTION
**Pull request by Zetabite**
Still needs ui resolve

### CODE REVIEW

**Comment by Zetabite** [comment]
The ui still needs some checking, i am not 100% that it will work.

**Comment by Zetabite** [comment]
So far this should work now

**Comment by jamierocks** [comment]
Hey Zetabite :wave: 

I've just opened GH-3597 which achieves the same goal but using the existing filter model and doesn't make further HTTP requests. It's also a fair bit smaller as a result.

**Comment by Zetabite** [comment]
*sigh*

**Comment by peterix** [comment]
Hmm. The other PR got merged.

**Pull request closed without merging**
