### PR TITLE
Add basic RPM package for RHEL-based Linux distros

### PR DESCRIPTION
**Pull request by ProjectSynchro**
Title.

I saw another pull request of this nature and figured I'd create one that doesn't require any source binaries to be built.

This is literally a carbon copy of the Debian package but for Fedora, should work for x86_64 and i386.

### CODE REVIEW

**Comment by peterix** [comment]
I think the package could actually be `noarch`, if that's still an RPM packaging concept.

**Comment by ProjectSynchro** [comment]
This is done, however it should only install on ix86 and x86_64 systems as ARM builds aren't available and it would be a bit weird to allow systems to install a package that doesn't work.

**Comment by peterix** [comment]
Nice :)

**Comment by dhalucario** [comment]
Is there a Repository available for this?

**Comment by ProjectSynchro** [comment]
@dhalucario I have a repository hosted on the Fedora Copr
Should work on all supported CentOS, Fedora, and SUSE releases.

https://copr.fedorainfracloud.org/coprs/jackgreiner/multimc/

**Comment by ifurther** [comment]
Dose it has CentOS 7 package ?

**Comment by ProjectSynchro** [comment]
Yes, there is a package for CentOS 7.

**Comment by ifurther** [comment]
OK, thank you

**Comment by Chronomly** [comment]
Any timeline on this being merged?

**Comment by Krutonium** [comment]
https://github.com/MultiMC/MultiMC5/commit/58c2228247c633805cdbe02ff97eb8cb6f3b3af7

Well they did this instead for some reason

**Comment by ProjectSynchro** [comment]
Well leave it to others to reinvent the wheel I suppose, closing this as it appears that clicking the merge button was harder than hastily rewriting this spec.

**Pull request closed without merging**
