### PR TITLE
NOISSUE Update Copyright Year

### PR DESCRIPTION
**Pull request by Scotsguy**
Skipped 2020, good riddance.

### CODE REVIEW

**Comment by AverageComet250** [comment]
Good job with the refactor, just make sure you haven't missed anything.

Just to clarify, this pull is just to change the copyright year 2021, right?

Thanks,
Shravan Mandava

________________________________

**Comment by Scotsguy** [comment]
I didn't do this manually and all the headers look the same, so I'd be surprised if I missed anything.

**Comment by kb-1000** [comment]
> all the headers look the same
That's not the case.

**Comment by Scotsguy** [comment]
They are similar enough to edit with a find and replace.

**Pull request merged**
