### PR TITLE
Added total playtime

### PR DESCRIPTION
**Pull request by lejliu**
Added a total playtime counter at the bottom (adds up playtime across all instances).
This is in response to https://github.com/MultiMC/MultiMC5/issues/2345 and https://github.com/MultiMC/MultiMC5/issues/2769.

### CODE REVIEW

**Comment by khuatduyhieu** [comment]
I know this is a weird question but how to remove the playtime?

**Comment by OsoaGitHub** [comment]
so uh... this ever getting added or not?

**Comment by Zetabite** [comment]
Have patience, peterix gets to it if he gets to it. It just not that relevant for the functionality of mmc and stuff msa support is more important right now.

**Comment by Janrupf** [comment]
Manually merged with https://github.com/MultiMC/MultiMC5/commit/1762d2fc7de99e38477a517c9b379447fd00b968

**Pull request closed without merging**
