### PR TITLE
AMIDST support

### PR DESCRIPTION
**Pull request by 02JanDal**
Depends on skiphs/AMIDST#22 (this should not be merged before that PR is merged).

### CODE REVIEW

**Comment by peterix** [comment]
We need that export of vanilla version files if this is ever supposed to work.

**Comment by peterix** [comment]
And to fix/redo external tools, because they've been ripped out.

**Comment by TheLoneWolfling** [comment]
skiphs/AMIDST#62 got merged recently. Any updates on this?

**Comment by peterix** [comment]
We don't have the version files for it to read anymore. They would have to be generated.

**Comment by Sxw1212** [comment]
How do we get this working?

**Comment by peterix** [comment]
newer version of amidst is here: https://github.com/toolbox4minecraft/amidst
Sadly it removes one of the options needed for integration...

Closing this, because the PR is really stale and would basically need a rework anyway.

**Pull request closed without merging**
