### PR TITLE
Update instance icons, using the newer minecraft textures

### PR DESCRIPTION
**Pull request by QazCetelic**

### CODE REVIEW

**Comment by UnlimitedCookies** [comment]
Some prefer the old icons, how about making both an option?

**Comment by peterix** [comment]
I would honestly prefer replacing them with something less lazy. This has been around for ... 8 years?
Maybe redo all the icons in the same style.

**Comment by peterix** [comment]
But you can replace them yourself right now if you like these more... Just put them in the icons folder.

**Comment by QazCetelic** [comment]
> I would honestly prefer replacing them with something less lazy. This has been around for ... 8 years?
> Maybe redo all the icons in the same style.

What about a 3d render of the blocks?

**Pull request merged**
