### PR TITLE
Added primitive search feature for mods

### PR DESCRIPTION
**Pull request by louis123456**
I implemented a search and download feature so you can download mods from CurseForge.

### CODE REVIEW

**Comment by louis123456** [comment]
I forgot to add a version select so you can select the version of the mod you like... So this is not ready yet

**Comment by louis123456** [comment]
This should be working now.

**Comment by Janrupf** [comment]
You should edit the commit message so they match the commit message scheme in MultiMC

**Comment by peterix** [comment]
I do not want this sort of integration with Twitch.

**Pull request closed without merging**
